### ISSUE TITLE
ICE: rewrite_func_ast:idate called with bad arguments

### ISSUE THREAD

**Issue by skrector** [flang-compiler/flang#357] opened 2018-01-07 19:20 UTC
I'm getting the error, "F90-F-0000-Internal compiler error. rewrite_func_ast:idate called with bad arguments       0".  When compiling an FORTRAN 77 program that uses the IDATE intrinsic function with three integer variables. I get the same error with both the 4.0 version and the 5.0 version. I've worked around the issue by using an array instead of the three integer variables. I can't post the original code because it isn't public, but I've included two working examples, one using integer variables and the other an array to work around the issue, and an example that generates the error.

flang --version
clang version 4.0.1 (https://github.com/flang-compiler/clang.git 94872eab7578af538341f30f2a85f3dc9952dda7) (https://github.com/llvm-mirror/llvm.git c8fccc53ed66d505898f8850bcc690c977a7c9a7)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/software/llvm/4.0/bin

Linux flang.localdomain 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

This works, compiled with "flang -w -static-flang-libs -o test test.f":
      PROGRAM TEST

      CHARACTER*8 ITIM

      CALL TIME(ITIM)
      ICENTRY = 2000
      CALL IDATE(IMONTH, IDAY, IYEAR)
      IYEAR = ICENTRY + MOD(IYEAR,100)

      WRITE(*, 15) IMONTH, IDAY, IYEAR, ITIM

 15   FORMAT(/6X, ' DATE: ',I2,'/',I2,'/'I4,' TIME: ',A8)

      STOP
      END

But it if I make any variable assignment, regardless of type, it generates the ICE. Compiled with, "flang -w -static-flang-libs -o test2 test2.f", this gives:
F90-F-0000-Internal compiler error. rewrite_func_ast:idate called with bad arguments       0  (test2.f: 10)
F90/x86-64 Linux Flang - 1.5 2017-05-01: compilation aborted

      PROGRAM TEST2

      CHARACTER*8 ITIM
      REAL MYFLT

      MYFLT=1.0

      CALL TIME(ITIM)
      ICENTRY = 2000
      CALL IDATE(IMONTH, IDAY, IYEAR)
      IYEAR = ICENTRY + MOD(IYEAR,100)

      WRITE(*, 15) IMONTH, IDAY, IYEAR, ITIM

 15   FORMAT(/6X, ' DATE: ',I2,'/',I2,'/'I4,' TIME: ',A8)

      STOP
      END

Changing the code to use an array works. Again compiled with, "flang -w -static-flang-libs -o test3 test3.f":
     PROGRAM TEST3

      CHARACTER*8 ITIM
      INTEGER*4 NOW(3)
      REAL MYFLT

      MYFLT=1.0

      CALL TIME(ITIM)
      ICENTRY = 2000
      CALL IDATE(NOW)
      IYEAR = ICENTRY + MOD(NOW(3),100)

      WRITE(*, 15) NOW(1), NOW(2), IYEAR, ITIM

 15   FORMAT(/6X, ' DATE: ',I2,'/',I2,'/'I4,' TIME: ',A8)

      STOP
      END

**Comment by gklimowicz** [comment] 2018-09-30 16:09
This appears to have been fixed in pull request #369 (Jan 24). I can't reproduce the problem with test2.f90 any more.

Please reopen if you have another reproducer.

Thank you.

**Closed by gklimowicz** 2018-09-30 16:09 UTC
Labels: nvidia
