### ISSUE TITLE
[F08] flang rejects polymorphic assignment

### ISSUE THREAD

**Issue by ghost** [flang-compiler/flang#512] opened 2018-06-23 15:38 UTC
Dear flang developers,

Having used flang 6.0 to compile a rather large OOP code base written in modern Fortran, flang's
Fortran 2003 support has proven to be much more mature than that of both gfortran 8.1 and 
ifort 18. Congratulations on a job well done!

That being said, there is an area where flang sadly lags behind these latter two compilers, namely
in that flang does not support Fortran 2008's polymorphic assignment. Consider the attached 
OOP code

```
module example

   implicit none
   
   private
   public :: Demo

   type :: Basetype
   contains
      procedure :: init => init_base
   end type Basetype
      
   type, extends(Basetype) :: Child1
      real(8), dimension(:), allocatable :: fltarr
   end type Child1

   type, extends(Basetype) :: Child2
      integer(4), dimension(:), allocatable :: intarr
   end type Child2

   ! main type to demonstrate polymorphic assignment
   type :: Demo
      class(Basetype), allocatable :: basevar1
      class(Basetype), allocatable :: basevar2      
   contains
      procedure :: init => init_demo
   end type Demo
   
   ! overloading of child types by constructor functions
   interface Child1
      procedure construct1
   end interface Child1
      
   interface Child2
      procedure construct2
   end interface Child2
      
contains

   function construct1(fltarr)
      !
      ! Constructor for objects of type Child1
      !
      type(Child1) :: construct1
      real(8), dimension(:), intent(in) :: fltarr      
      call construct1%init(fltarr=fltarr)
   end function construct1
   
   function construct2(intarr)
      !
      ! Constructor for objects of type Child2
      !
      type(Child2) :: construct2
      integer(4), dimension(:), intent(in) :: intarr
      call construct2%init(intarr=intarr)
   end function construct2

   subroutine init_base(self,fltarr,intarr)
      !
      !  Initializes children of Basetype
      !
      class(Basetype), intent(inout) :: self
      real(8),    dimension(:), intent(in), optional :: fltarr
      integer(4), dimension(:), intent(in), optional :: intarr
      select type ( self )
      class is ( Child1 )
         if ( present(fltarr) ) self%fltarr = fltarr
      class is ( Child2 )
         if ( present(intarr) ) self%intarr = intarr
      class default
         stop 'Type not supported!'
      end select
   end subroutine init_base
   
   subroutine init_demo(self,fltarr,intarr)
      !
      !  Initializes objects of type Demo
      !
      class(Demo), intent(inout) :: self
      real(8),    dimension(:), intent(in) :: fltarr
      integer(4), dimension(:), intent(in) :: intarr
      self%basevar1 = Child1(fltarr)
      self%basevar2 = Child2(intarr)
   end subroutine init_demo
         
end module example
```
This code compiles under gfortran and ifort, but is rejected by flang with the warnings:
```
F90-S-0155-Left hand side of assignment cannot be polymorphic - basevar1 (example.F08: 82)
F90-S-0099-Illegal use of derived type (example.F08: 82)
F90-S-0155-Left hand side of assignment cannot be polymorphic - basevar2 (example.F08: 83)
F90-S-0099-Illegal use of derived type (example.F08: 83)
  0 inform,   0 warnings,   4 severes, 0 fatal for init_demo

```
forcing one to change the subroutine init_demo to use sourced allocation as a stop-gap measure,
as follows:
```
   subroutine init_demo(self,fltarr,intarr)
      !
      !  Initializes objects of type Demo
      !
      class(Demo), intent(inout) :: self
      real(8),    dimension(:), intent(in) :: fltarr
      integer(4), dimension(:), intent(in) :: intarr
      allocate(self%basevar1, source=Child1(fltarr))
      allocate(self%basevar2, source=Child2(intarr))
   end subroutine init_demo

```
This makes developing object-oriented code extremely awkward. With large code bases, hundreds of sourced allocation statements, like the above can become necessary, leading to almost completely unreadable code, especially if allocatable variables like basevar1/basevar2 above have already been
allocated and need to be reinitialized (requiring the use of a deallocate statement, before sourced allocation can/must be used anew).

Please consider supporting polymorphic assignment as one of the first Fortran 2008 features.
Leaving polymorphic assignment out of the Fortran 2003 standard was possibly the greatest
oversight made at that time by WG5.

Moreover, compared to the effort required to implement other Fortran 2008 features, like Co-arrays, polymorphic assignment should be rather "low-hanging" fruit.

Regards

**Comment by cfdtech** [comment] 2018-08-17 13:50
@janusw - Why this snide comment?

I do not only stand behind my statements, I even emphasize them once more here: flang (and for what it's worth pgfortran) are more mature than both gfortran and ifort when it comes to producing bug-free Fortran 2003 object code.

Sorry that this doesn't fit your worldview, but gfortran is a buggy mess when it comes to modern Fortran support. Since April, I have submitted four bug reports to gfortran Bugzilla (I could have submitted even more, but at some point I just stopped bothering with gfortran). At least two of said bugs were show-stopping bugs, for which I couldn't  come up with some work-around. Out of these bugs only _one_ has been fixed to date (an internal compiler error, a regression back from version 4.x or so). 

When it comes to bug fixing, my experience with the gfortran developers is that they are primarily interested in fixing known regressions. Other reported bugs linger in Bugzilla for months to years!
This is extremely disappointing for an open source project.

With gfortran I sometimes still hit cases (i.e. perfectly valid Fortran 2003) that the compiler simply is not able to compile (let alone execute). I essentially never had this problem with flang. I am not even going to mention Intel's compiler here, as it is even less capable to compile perfectly valid object-oriented Fortran code.

If it were not for flang I wouldn't be able to use Fortran 2003 features at all, and I use most of them. I don't know which features you tend to use heavily, but my project is of order 30 KSLOC (all modern Fortran), and I have gone through repeated massive refactorings of that code base, only to find that flang (and pgfortran) are currently the only compilers capable of keeping up with such real-world demands. So, I think my statements above are rather informed.

If it were not for flang, and given the mess that other compilers are in right now, I would have left Fortran development altogether last year. Flang has saved me from moving to C++ (yikes!). So I extend again my thanks to the flang developers:

Thank you, you keep my project going!

**Comment by janusw** [comment] 2018-08-17 16:00
My comment wasn't meant to be snide, sorry if it came across like that. Your statement was simply a bit too strong for my taste. I've seen quite a few code bases that work with gfortran and/or ifort, but not with PGI/flang. In any case, I'm perfectly aware that such things are highly subjective, and I certainly don't want to start a debate about which one is the best compiler. Depending on your metric and your requirements, you can get very different answers to that question, so let's not go into that discussion.

Also: Yes, I contribute to gfortran. But no, it's not "my own house". I simply have an interest in having a good open-source Fortran2018 compiler available (no matter if it's called gfortran or flang), and I assume I share that interest with you. You have to understand that I'm not taking orders from you, though. I'm kinda allergic to people who assume that it's my obligation to fix their bugs. To clear up your misunderstanding: It's not.

**Comment by cfdtech** [comment] 2018-08-17 16:11
@janusw - If you re-read my post, you'll notice that I haven't ordered you to do anything. I just made a suggestion for the benefit of the gfortran project. Thankfully, we now have an alternative, so it's up to the gfortran developers/contributors what to make of the feedback of unsatisfied users. In any case, let's cut this discussion here. This is not the place for it.

Regards

**Comment by gklimowicz** [comment] 2019-10-03 20:03
We believe the recent commits to Flang resolve this issue. Please reopen if you find that it is not.

**Closed by gklimowicz** 2019-10-03 20:03 UTC
Labels: enhancement, nvidia, verify
