### ISSUE TITLE
dbcsr: flang did not notice that pure function defined later in the 'contains' section is pure

### ISSUE THREAD

**Issue by pawosm-arm** [flang-compiler/flang#1016] opened 2021-03-25 12:44 UTC
Consider the following piece of Fortran code:

```
module mymod
  implicit none
  private
  public :: func, other_func
  type :: foo
    integer :: mydim
  end type

contains

subroutine func(tparam, oparam)
  type(foo), intent(in) :: tparam
  integer, dimension(other_func(tparam, 1)), intent(out), optional :: oparam

  oparam = 42
end subroutine

pure function other_func(tparam, idim)
  type(foo), intent(in) :: tparam
  integer, intent(in) :: idim
  integer :: other_func

  other_func = min(tparam%mydim, idim)
end function

end module
```

Note that gfortran can compile this code, while flang can not:

```
F90-S-0084-Illegal use of symbol other_func  (mymod.f90: 13)
  0 inform,   0 warnings,   1 severes, 0 fatal for func
```

Yet when the pure function `other_func` definition is moved before it is used (in a place where a pure function should be called), flang is able to compile it:

```
contains

pure function other_func(tparam, idim)
  type(foo), intent(in) :: tparam
  integer, intent(in) :: idim
  integer :: other_func

  other_func = min(tparam%mydim, idim)
end function

subroutine func(tparam, oparam)
  type(foo), intent(in) :: tparam
  integer, dimension(other_func(tparam, 1)), intent(out), optional :: oparam

  oparam = 42
end subroutine
```

**Comment by abrahamtovarmob** [comment] 2021-07-06 11:51
Error possible root cause is because the value getting by 
`STYPEG(sptr)`
Is not found in the switch() condition inside semutil.c:
`switch (STYPEG(sptr)) {`
The current value is set to ST_MODPROC
The value is being set at:
```
do_access() at semfin.c:1,288 0x6c917b	

rsptr	int	626	
sptr	int	626	
a	int	1	
encl	int	0	
ssptr	int	9745480	
sptrmem	int	1	
nsyms	int	629	
stype	int	0	
accessp	ACCL *	0x9142b8	

stype = STYPEG(sptr);
    switch (stype) {
    case ST_UNKNOWN:
      if (in_module) {  -->> unknown type inside a module
        if (sem.none_implicit) {
          /* can't be a variable, wouldn't be an unknown */
          SPTR sptr2 = findByNameStypeScope(SYMNAME(sptr), ST_INTRIN, 0);    --->>>  sptr2	SPTR	SPTR_NULL	

          if (sptr2 > NOSYM && sptr != sptr2) {    //-->>> expression evaluation is FALSE
...
          }
          STYPEP(sptr, ST_MODPROC);  
...
```

For that the check fails and it gives the error.
One way to fix it is to add the required CASE conditions for that expression be recognized. The points where code should be added is at:
```
tools/flang1/flang1exe/semutil.c
@@ -1172,6 +1174,11 @@ again:
             "- attempt to use a GENERIC subprogram as a FUNCTION");
       SST_DTYPEP(stkptr, DT_INT);
       return 1;
+// >>>>>>>>>>>>>>>>>>>>>>>>>>>> something TODO, possible fix for 1016
+    case ST_MODPROC:
+      dtype = DTYPEG(sptr);
+
+      break;
     default:
       error(84, 3, gbl.lineno, SYMNAME(sptr), CNULL);
       SST_DTYPEP(stkptr, DT_INT);
@@ -2146,6 +2156,12 @@ mkvarref(SST *stktop, ITEM *list)
       ref_pd(stktop, list);
       return 1;
 
+// >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> possible fix for issue 1016
+    case ST_MODPROC:
+      dtype = DTYPEG(sptr);
+      //TODO?
+      break;
+
     default:
       dtype = DTYPEG(sptr);
       /* illegal use */
```
I need advice on what code should be added.
The other possible solution is to change the type from ST_MODPROC to some category that is already recognized.

**Comment by abrahamtovarmob** [comment] 2021-07-16 13:53
Root cause:
There is a reduction calculation done when parsing the code:
parser.c :: static void _parser(void) {
```
...
      LOOP
      {
        /*
         * perform binary search on parse tables to determine if a
         * reduction can be made:
         */
        start = fred[cstate];
        end = fred[cstate + 1] - 1;
        if (start > end)
          break; /* no reduction */
        for (i = start; i <= end; i++) {
          jstart = lset[nset[i]];
          jend = lset[nset[i] + 1] - 1;
          while (jstart <= jend) {
            ptr = (jstart + jend) >> 1;
            t = ls[ptr];
            if (t == tkntyp)
              goto perform_reduction;
            if (t < tkntyp)
              jstart = ptr + 1;
            else
              jend = ptr - 1;
          }
        }
        break; /* no reduction found */

```
After this reduction calculation, it calculates a value called "rednum", based in the number of iterarions that the loop had previously
```
      perform_reduction:
        rednum = prod[i];
```
Then it comes a decision tree to find out the category of the found syntaxis
```
       if (rednum < SEM2)
          p_semant1[sem.which_pass](rednum, &sst[newtop]);
        else if (rednum < SEM3)
          p_semant2[sem.which_pass](rednum, &sst[newtop]);
```
In the case of the WorkAround, the values are:
```
tkntyp	int	384	
newtop	int	3	
rednum	int	52	
endflg	int	0	
t	int	384	
start	int	37	
end	int	37	
nstate	int	42	
jstart	int	4714	
jend	int	4714	
ptr	int	4714	
i	int	37
```
in the case of the Issue, the values are:
```
tkntyp	int	15	
newtop	int	7	
rednum	int	701	
endflg	int	0	
t	int	15	
start	int	1296	
end	int	1296	
nstate	int	1752	
jstart	int	276	
jend	int	276	
ptr	int	276	
i	int	1296	
```
Because of the value for "rednum" is 52, the data flow goes to the p_semant1(), in the case of the error it goes to p_semant2(), the latest function doesn't have the option for ST_MODPROC and hence the error in the screen.

We need to verify that the calculation of rednum is correct, in this case depends on proc[i] that eventually just depend on i. The other option is to check if the array proc[] is being filled properly but I don't think that can be the issue.

**Comment by michalpasztamobica** [comment] 2021-07-16 16:04
@abrahamtovarmob , you can find the explanation of the rednum (reduction number) in `build/tools/flang1/utils/prstab/proddf.h` (search by line number...) or in `gramsm.h`:
```
    "<prefix> ::= PURE |",   // Sounds good, considering the issue title
...
    "<var ref> ::= <var primary ssa> ( <ssa list> )  |",
```
These will make more sense if you find them in `gram.txt`.

The tkntyp (token type) can be deciphered by looking into `build/tools/flang1/utils/prstab/gramtk.h`:
```
#define TK_RPAREN                               15
...
#define TK_FUNCTION                            384
```
So in one case you get right parenthesis recognized and in the other you get function recognized.

From this point you can either check if there is a bug in the parser (effectively in how the `gram.txt` is written) or you can analyze how there two tokens and reductions are handled. 
I don't fully understand the division between `semant1` and `semant2`, but I think it is a rather incidental division to keep the functions smaller...

Can you check the `gbl.lineno` variable to make sure we're looking at the problematic line, and not it's consequence?
Also - please compare what are the reductions before and optionally after these ones. Perhaps the same reductions happen in both cases just a little later? I imagine that the pure function could be recognized, but the earlier processing somehow corrupts the way it is handled.

**Comment by abrahamtovarmob** [comment] 2021-07-19 12:40
Thanks @michalpasztamobica for the help, that was a good tip indeed.
I'm debugging the same 'equivalent' lines, i.e. line 13 in the 'error' file and line 21 in the 'workaround' file.

We find out that it's doing the same reduction (rednum = 266) But once inside the function p_semant1() there is a slight difference.
After some checks and decision trees it comes to this code:
mkexpr1() at semutil.c:993 0x74a646	
```
...
switch (SST_IDG(stkptr)) {
...
```
In the case of the WA, SST_IDG = 2, because stkptr->id = 2, in the case of the error the Value is 7
Because of this, the Error goes to this code:
```
...
case S_IDENT:
    /* need to set data type, stack type */
    dtype = 0;
    sptr = SST_SYMG(stkptr);
    shape = 0;
    get_next_hash_link(sptr, 0);
  retry:
    i = STYPEG(sptr);
    switch (STYPEG(sptr)) {
...
```
And after this switch is when it cannot find the CASE for ST_MODPROC and hence the error.

I need to find out why stkptr->id = 7, I think in the assignation can be the error

**Comment by abrahamtovarmob** [comment] 2021-07-20 15:20
Almost all the reduction numbers are identical, but the divert start with this one:
WA
```
gbl.lineno	int	21	
tkntyp	int	15	
rednum	int	707	
sst	SST *	0x95ce60	
sst->id	short	15600	
top	SST *	0x95d058	
top->id	short	7	
stktop	int	11	
i	int	0	
sptr	int	10328	

gbl.lineno	int	21	
tkntyp	int	15	
rednum		701
sst	SST *	0x95ce60	
sst->id	short	15600	
top	int	0	
top->id		7
stktop	SST *	0x95cfe8	
stktop->id	short	7	
i	int	14	
sptr	int	633
```
ERROR
```
gbl.lineno	int	13	
tkntyp	int	15	
rednum	int	707	
sst	SST *	0x95ae40	
sst->id	short	0	
top	SST *	0x95b038	
top->id	short	7	
stktop	int	11	
i	int	0	
sptr	int	10328	

gbl.lineno	int	13	
tkntyp	int	15	
rednum		701
sst	SST *	0x95ae40	
sst->id	short	0	
top	int	0	
top->id		7
stktop	SST *	0x95afc8	
stktop->id	short	7	
i	int	27	
sptr	int	626	
```
Here the value of i is  
```
i = STYPEG(sptr);
    switch (STYPEG(sptr)) {
```
the call stack for Workaround:
mkvarref() at semutil.c:1,969 0x74db09	
semant2() at semant2.c:1,248 0x691e9f	
_parser() at parser.c:325 0x5eb1d4	
parser() at parser.c:120 0x5eaa83	
main() at main.c:208 0x5b6274	

the call stack for error:
mkvarref() at semutil.c:2,175 0x74eb84	
semant2() at semant2.c:1,248 0x691e9f	
_parser() at parser.c:325 0x5eb1d4	
parser() at parser.c:88 0x5eaa07	
main() at main.c:208 0x5b6274	

(stb.stg_base[s].stype) = 14 and this is ST_FUNC. So the error is that the code is being identified as ST_MODPROD. I will check how is the workaround identifying as ST_FUNC

**Comment by abrahamtovarmob** [comment] 2021-07-21 11:05
I see this behaviour in the "error" code
```
module mymod
  implicit none
  private
  public :: func, other_func
  type :: foo
    integer :: mydim
  end type

contains                                                                                                                  >>> From this section, code is  ST_MODPROC

subroutine func(tparam, oparam)
  type(foo), intent(in) :: tparam
  integer, dimension(other_func(tparam, 1)), intent(out), optional :: oparam          >>> Error flagged

  oparam = 42
end subroutine                                                                                                       >>> From this section, code is ST_PROC

pure function other_func(tparam, idim)
  type(foo), intent(in) :: tparam
  integer, intent(in) :: idim
  integer :: other_func

  other_func = min(tparam%mydim, idim)
end function

end module
```
In order to pass the error, the "subroutine ..." code should be ST_PROC. In case subroutine is correctly labeled as ST_MODPROD, then we need to add an exception when (stb.stg_base[s].stype) is being evaluated and some how filter it for this particular case.

**Comment by michalpasztamobica** [comment] 2021-07-21 12:43
So `ST_MODPROC` stands for "module procedure". `other_func` is effectively a "module procedure" of module `mymod`. I am wondering if the fix for this issue should perhaps simply be:
```
--- a/tools/flang1/flang1exe/semutil.c
+++ b/tools/flang1/flang1exe/semutil.c
@@ -2007,6 +2007,7 @@ mkvarref(SST *stktop, ITEM *list)
       goto add_base;
 
     case ST_PROC:
+    case ST_MODPROC:
       if (FVALG(sptr) == 0 && DTYPEG(sptr) == 0) {
         error(84, 3, gbl.lineno, SYMNAME(sptr),
               "- attempt to use a SUBROUTINE as a FUNCTION");
```
With the above patch, I got this example fixed and all tests still passing with `make check-all`.

**Comment by abrahamtovarmob** [comment] 2021-07-21 13:30
This is how the WA manage to work:
```
module mymod
  implicit none
  private
  public :: func, other_func
  type :: foo
    integer :: mydim
  end type

contains                                                 >>> type ST_MODPROC assigned

pure function other_func(tparam, idim)
  type(foo), intent(in) :: tparam
  integer, intent(in) :: idim
  integer :: other_func

  other_func = min(tparam%mydim, idim)
end function                                         >>> type ST_PROC assigned

subroutine func(tparam, oparam)
  type(foo), intent(in) :: tparam
  integer, dimension(other_func(tparam, 1)), intent(out), optional :: oparam   >> checks for other_func, passes because is type ST_PROC

  oparam = 42
end subroutine                                       >>> type ST_PROC assigned

end module
```

The root cause is that when it checks 'other_func' is being marked as ST_MODPROC, but when it comes 'end subroutine' it changes to ST_PROC

One way to fix this is to assign ST_PROC when subroutine is detected, but I think there is an architectural reason why only changes occur at the 'end...' parts.

The other fix is as Michal mention, to add ST_MODPROC into the decision tree

**Comment by abrahamtovarmob** [comment] 2021-07-26 07:24
Fix discussed with @paulwalker-arm and agreed on how to proceed. Code patched and test added.
Tests before the patch:
Testing Time: 259.70s
  Expected Passes    : 1360
  Expected Failures  : 1
  Unsupported Tests  : 34
Built target check-all

Tests after the patch:
Testing Time: 188.25s
  Expected Passes    : 1361
  Expected Failures  : 1
  Unsupported Tests  : 34
Built target check-all

Code will be pushed for review in a PR

**Closed** 2021-08-10 20:37 UTC
