### ISSUE TITLE
flang fails to build test with field initializers

### ISSUE THREAD

**Issue by shivaramrao** [flang-compiler/flang#563] opened 2018-08-10 12:36 UTC
the following test gives following error

F90-S-0091-Constant expression of wrong data type (t15.f90: 25)

when the fields of 2nd structure are reversed, the test passes.

not working test:
!!!
MODULE dbcsr_types
   IMPLICIT NONE
   INTEGER, PARAMETER :: dp = SELECTED_REAL_KIND(14, 200)
   TYPE dbcsr_mempool_entry_type
       INTEGER :: i1 = 10
   END TYPE dbcsr_mempool_entry_type
   TYPE dbcsr_memtype_type
      TYPE(dbcsr_mempool_entry_type), POINTER :: pool => Null()
      REAL(KIND=8)                     :: oversize_factor  = 1.0
   END TYPE dbcsr_memtype_type
   PUBLIC :: dbcsr_type
   TYPE dbcsr_type
      TYPE(dbcsr_memtype_type)                     :: data_memory_type = dbcsr_memtype_type()
   END TYPE dbcsr_type
ND MODULE dbcsr_types

!!!
working test
MODULE dbcsr_types
   IMPLICIT NONE
   INTEGER, PARAMETER :: dp = SELECTED_REAL_KIND(14, 200)
   TYPE dbcsr_mempool_entry_type
       INTEGER :: i1 = 10
   END TYPE dbcsr_mempool_entry_type
   TYPE dbcsr_memtype_type
      REAL(KIND=8)                     :: oversize_factor  = 1.0
      TYPE(dbcsr_mempool_entry_type), POINTER :: pool => Null()
   END TYPE dbcsr_memtype_type
   PUBLIC :: dbcsr_type
   TYPE dbcsr_type
      TYPE(dbcsr_memtype_type)                     :: data_memory_type = dbcsr_memtype_type()
   END TYPE dbcsr_type
ND MODULE dbcsr_types

**Comment by pawosm-arm** [comment] 2018-08-10 17:34
Duplicated bug: see my additional reproduction case for bug #239: https://github.com/flang-compiler/flang/issues/239#issuecomment-395998806

**Comment by shivaramrao** [comment] 2018-08-10 18:05
Thanks. the issue is same as bug #239. the origin of testcase is cp2k dbcsr_data_types.f90

**Comment by gklimowicz** [comment] 2018-08-16 15:52
Since this is a duplicate, I will close this issue.

**Closed by gklimowicz** 2018-08-16 15:52 UTC
